import { Geist, Geist_Mono } from "next/font/google";

import { stackServerApp } from "../stack";
import "./globals.css";
import Provider from "./provider";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <Suspense fallback={<div>Loading...</div>}>
          <StackProvider app={stackServerApp}>
            <StackTheme>
              <Provider>{children}</Provider>
            </StackTheme>
          </StackProvider>
        </Suspense>
      </body>
    </html>
  );
}
